<?php
// Page-specific data
$page_title = "RAIS Admin - Application Management";
$active_page = "application_management"; // Used to set the 'active' class in the sidebar

// In a real application, this data would be fetched from your database.
$applications = [
    ['id' => 'APP-001', 'userName' => 'John Doe', 'type' => 'Visa Application', 'date' => '2024-07-28', 'status' => 'Pending Review', 'fileUrl' => '#'],
    ['id' => 'APP-002', 'userName' => 'Jane Smith', 'type' => 'Work Permit', 'date' => '2024-07-27', 'status' => 'Approved', 'fileUrl' => '#'],
    ['id' => 'APP-003', 'userName' => 'Peter Jones', 'type' => 'Study Permit', 'date' => '2024-07-25', 'status' => 'Cancelled', 'fileUrl' => '#'],
    ['id' => 'APP-004', 'userName' => 'Alice Brown', 'type' => 'Visa Application', 'date' => '2024-07-22', 'status' => 'Pending Review', 'fileUrl' => '#']
];

?>
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($page_title); ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="icon" href="../img/logoulit.png" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;900&display=swap"
        rel="stylesheet">
   <link rel="stylesheet" href="style.css">
</head>

<body>
    <div class="main-wrapper">
        
        <?php require_once 'sidebar.php'; ?>

        <div class="content-area">
            
            <?php require_once 'header.php'; 
            ?>

            <!-- Main Content -->
            <main class="main-content">
                <h1>Application Management</h1>

                <div class="content-card">
                    <div class="d-flex flex-column flex-md-row justify-content-between align-items-center mb-3">
                        <h2 class="mb-3 mb-md-0">Submitted Applications</h2>
                        <div class="input-group w-100" style="max-width: 400px;">
                            <input type="text" class="form-control" placeholder="Search by ID, name or type..."
                                id="searchInput">
                            <button class="btn btn-outline-secondary" type="button"><i class="bi bi-search"></i></button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">User Name</th>
                                    <th scope="col">Application Type</th>
                                    <th scope="col">Submitted</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody id="applicationsTableBody">
                                <?php
                                // The table body is now generated by PHP.
                                foreach ($applications as $app) {
                                    $statusBadge = '';
                                    switch ($app['status']) {
                                        case 'Approved':
                                            $statusBadge = 'bg-success';
                                            break;
                                        case 'Pending Review':
                                            $statusBadge = 'bg-warning text-dark';
                                            break;
                                        case 'Cancelled':
                                            $statusBadge = 'bg-danger';
                                            break;
                                        default:
                                            $statusBadge = 'bg-secondary';
                                    }

                                    echo "<tr>";
                                    echo "<td>" . htmlspecialchars($app['id']) . "</td>";
                                    echo "<td>" . htmlspecialchars($app['userName']) . "</td>";
                                    echo "<td>" . htmlspecialchars($app['type']) . "</td>";
                                    echo "<td>" . htmlspecialchars($app['date']) . "</td>";
                                    echo "<td><span class=\"badge " . $statusBadge . "\">" . htmlspecialchars($app['status']) . "</span></td>";
                                    echo '<td>
                                            <a href="' . htmlspecialchars($app['fileUrl']) . '" class="btn btn-sm btn-outline-primary" download><i class="bi bi-download"></i></a>
                                            <button class="btn btn-sm btn-success approve-btn" data-id="' . htmlspecialchars($app['id']) . '"><i class="bi bi-check-lg"></i></button>
                                            <button class="btn btn-sm btn-danger cancel-btn" data-id="' . htmlspecialchars($app['id']) . '"><i class="bi bi-x-lg"></i></button>
                                          </td>';
                                    echo "</tr>";
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>

            </main>
        </div>
    </div>

    <!-- Bootstrap JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <script src="togglemodeScript.js"></script>
    
    <!-- Page-specific script for search functionality -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const searchInput = document.getElementById('searchInput');
            const tableBody = document.getElementById('applicationsTableBody');
            const tableRows = tableBody.getElementsByTagName('tr');

            searchInput.addEventListener('keyup', function () {
                const searchTerm = this.value.toLowerCase();

                for (let i = 0; i < tableRows.length; i++) {
                    const row = tableRows[i];
                    // Get text from all cells except the last one (actions)
                    const rowText = (row.cells[0].textContent + ' ' + row.cells[1].textContent + ' ' + row.cells[2].textContent).toLowerCase();
                    
                    if (rowText.includes(searchTerm)) {
                        row.style.display = ""; // Show the row
                    } else {
                        row.style.display = "none"; // Hide the row
                    }
                }
            });

            // You can add event listeners for your approve/cancel buttons here
            // For example:
            // tableBody.addEventListener('click', function(event) {
            //     if (event.target.closest('.approve-btn')) {
            //         const appId = event.target.closest('.approve-btn').dataset.id;
            //         console.log('Approve clicked for ID:', appId);
            //         // Add your approve logic here (e.g., an AJAX call)
            //     }
            // });
        });
    </script>

</body>

</html>